### PR TITLE
feat: add simple prettier config

### PR DESCRIPTION
**Pull request by LexSwed**
This PR adds prettier eslint integration.

Next steps:

- [ ] agree on basic rules
  - [ ] [printWidth](https://prettier.io/docs/en/options.html#print-width) (default: 80)
  - [ ] [tabWidth](https://prettier.io/docs/en/options.html#tab-width) (default: 2)
  - [ ] [Print semicolons at the ends of statements.](https://prettier.io/docs/en/options.html#semicolons) (default: true)
  - [ ] [singleQuote](https://prettier.io/docs/en/options.html#quotes) (default: false)
  - [ ] [quoteProps](https://prettier.io/docs/en/options.html#quote-props) (default: "as-needed")
  - [ ] [jsxSingleQuote](https://prettier.io/docs/en/options.html#jsx-quotes) (default: false)
  - [ ] [trailingComma](https://prettier.io/docs/en/options.html#trailing-commas) (default: "es5")
  - [ ] [bracketSpacing](https://prettier.io/docs/en/options.html#bracket-spacing) (default: true)
  - [ ] [jsxBracketSameLine](https://prettier.io/docs/en/options.html#jsx-brackets) (default: false)
  - [ ] [arrowParens](https://prettier.io/docs/en/options.html#arrow-function-parentheses) (default: "always")
- [ ] release under `@next`
- [ ] try out in few repos with and without prettier installed

### CODE REVIEW

**Comment by mathio** [comment]
I think width 80 is too low and actually decreases code readability.

Semicolons - now that I finally got used to the syntax without semicolons? 🤣 Why do you want to change it?

**Comment by LexSwed** [comment]
> I think width 80 is too low and actually decreases code readability.
> 
> Semicolons - now that I finally got used to the syntax without semicolons? 🤣 Why do you want to change it?

Hey man. None of this is final, I thought of making an annoucment for everyone interested to come here and leave a comment in the format of the `rule`, `proposed value`, why.

**Comment by antoniofull** [comment]
> > I think width 80 is too low and actually decreases code readability.
> > Semicolons - now that I finally got used to the syntax without semicolons? 🤣 Why do you want to change it?
> 
> Hey man. None of this is final, I thought of making an annoucment for everyone interested to come here and leave a comment in the format of the `rule`, `proposed value`, why to change the default.
> 
> My example:
> 
> `printWidth`: set to `100` or `120` because we're not in 90s
> `singleQuote`: set to `true`, as it's easier to tap one button and not two. And we can never have consistency anyway, because for one rule it's `"Hello \"citation\""` prettified to `'Hello \"citation\"'` and for another it's `'What\'s up?'` prettified to `"What's up?"`

- I also think 80 might be too low, 120 seems to be a good deal.
- Changing semicolons now would make a lot of pr hard to review and add a lot of extra changes
- I'd leave the single quotes for jsx (but that's is more a personal preference I am fine with keeping it to false too)
- Arrow parens, if I am not mistaken that means when one single parameter is passed we keep the parenthesis?

**Comment by antoniofull** [comment]
BTW: I really like the step by step commits, great job! 💯

**Comment by scabfos** [comment]
printWidth: 120
 tabWidth 2
 Print semicolons at the ends of statements. : false
 singleQuote: true
 quoteProps: 'as-needed'
 jsxSingleQuote: true
 trailingComma: 'es5'
 bracketSpacing: true
 jsxBracketSameLine: false
 arrowParens: 'avoid'

This would be my propsal 👌

**Comment by otorrillas** [comment]
> * Changing semicolons now would make a lot of pr hard to review and add a lot of extra changes

@antoniofull to address this, maybe what we can do is format all `src/*` in the same PR we bring `prettier` and _new_ `eslint` config?

**Comment by antoniofull** [comment]
> > * Changing semicolons now would make a lot of pr hard to review and add a lot of extra changes
> 
> @antoniofull to address this, maybe what we can do is format all `src/*` in the same PR we bring `prettier` and _new_ `eslint` config?

Yup that is great idea! 
I personally alway worked with semicolons in the past, but I would fine also in not using them like we do now.  My only opinion on that is that this point should not be left optional:  either we go for it or not 😄

**Comment by rogerclotet** [comment]
Am I the only one to prefer double quotes for jsx? 😅 I like to read it in a similar way you would read pure HTML, but it's not a big deal.

For line length, I also agree to set it to `120`.

I wouldn't change semicolons at the ends of statements. They don't add anything and there would be a lot of (unnecessary) changed lines.

Agree with the rest :) Good initiative!

**Comment by heliosam** [comment]
I like @scabfos proposal 👍  

I would love to have double quotes on jsx `jsxSingleQuote: false`, but that would have almost the same effect of adding semicolons: meaning that there would be hundreds of code changes across all projects.

**Comment by LexSwed** [comment]
Closing this as decided to keep standard-js for code style and prettier does not allow to modify settings to be same as standard.
Path forward is to use `prettier-standard`

**Pull request closed without merging**
